Allure reporting (6/n)

diff --git a/.github/workflows/ui-tests.yml b/.github/workflows/ui-tests.yml
--- a/.github/workflows/ui-tests.yml
+++ b/.github/workflows/ui-tests.yml
@@ -41,18 +41,16 @@ jobs:
       - name: Run Selenium Tests
         run: dotnet test ./SeleniumTestFramework.csproj --logger "console;verbosity=normal"
         continue-on-error: true
-        env:
-          ALLURE_RESULTS_DIRECTORY: ${{ github.workspace }}/allure-results
 
       - name: List allure-results
-        run: dir "${{ github.workspace }}\allure-results" || echo "allure-results not found"
+        run: dir bin\Debug\net8.0\allure-results || echo "allure-results not found"
         continue-on-error: true
 
       - name: Install Allure CLI
         run: npm install -g allure-commandline
 
       - name: Generate Allure Report
-        run: allure generate "${{ github.workspace }}/allure-results" --clean -o allure-report
+        run: allure generate bin/Debug/net8.0/allure-results --clean -o allure-report
 
       - name: Upload Allure Report
         uses: actions/upload-artifact@v4
